<a href="https://colab.research.google.com/github/iai-project/AAAI22-one-shot-talking-face/blob/main/array_gpu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=tf.float16)
print(tensor, "\n")
# Tensor同士の行列積を計算する tf.matmul
result = tf.matmul(tensor, tensor)
print(result)


tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float16) 

tf.Tensor(
[[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]], shape=(3, 3), dtype=float16)


In [ ]:
import tensorflow as tf
tensor = tf.constant([[False, True, False], [True, True, True], [False, False, False]])
print(tensor, "\n")
# Tensor同士の行列積を計算する tf.matmul
result = tf.matmul(tensor, tensor)
#result = tensor @ tensor
print(result)

tf.Tensor(
[[False  True False]
 [ True  True  True]
 [False False False]], shape=(3, 3), dtype=bool) 



InvalidArgumentError: ignored

In [ ]:
import tensorflow as tf

x = tf.constant([[True,  True], [False, False]])
print(x, "\n")

z1 = tf.identity(x)
z2 = tf.reduce_all(x)
z3 = tf.reduce_all(x,0)
z4 = tf.reduce_all(x,1)

#sess = tf.Session()
#out = sess.run([z1,z2,z3,z4])
print(z1)
print(z2)
print(z3)
print(z4)

tf.Tensor(
[[ True  True]
 [False False]], shape=(2, 2), dtype=bool) 

tf.Tensor(
[[ True  True]
 [False False]], shape=(2, 2), dtype=bool)
tf.Tensor(False, shape=(), dtype=bool)
tf.Tensor([False False], shape=(2,), dtype=bool)
tf.Tensor([ True False], shape=(2,), dtype=bool)


In [ ]:
import tensorflow as tf

# 2つのbool型の行列を定義
matrix1 = tf.constant([[True, False], [False, True]])
matrix2 = tf.constant([[False, True], [True, True]])

print(matrix1, "\n")
print(matrix2, "\n")

# 論理積を計算
result = tf.logical_and(matrix1, matrix2)

print(result)

# Trueの要素の数を数える
true_count = tf.reduce_sum(tf.cast(result, tf.int32))
print(true_count)

# 結果を評価する
true_count.numpy()

tf.Tensor(
[[ True False]
 [False  True]], shape=(2, 2), dtype=bool) 

tf.Tensor(
[[False  True]
 [ True  True]], shape=(2, 2), dtype=bool) 

tf.Tensor(
[[False False]
 [False  True]], shape=(2, 2), dtype=bool)
tf.Tensor(1, shape=(), dtype=int32)


1

In [ ]:
import tensorflow as tf

# 1000行1000列のランダムな値を持つ行列を生成
# 生成される値は0から1の間
random_matrix1 = tf.random.uniform(shape=(1000, 1000), minval=0, maxval=1)
random_matrix2 = tf.random.uniform(shape=(1000, 1000), minval=0, maxval=1)

# 0.5を閾値として、それより大きい値をTrue、それ以下をFalseに変換
bool_matrix1 = random_matrix1 > 0.5
bool_matrix2 = random_matrix2 > 0.5

# 結果のbool型行列を表示
print(bool_matrix1)
print(bool_matrix2)

# 論理積を計算
result = tf.logical_and(bool_matrix1, bool_matrix2)
print(result)

# Trueの要素の数を数える
true_count = tf.reduce_sum(tf.cast(result, tf.int32))
print(true_count)

# 結果を評価する
true_count.numpy()

tf.Tensor(
[[ True  True False ...  True False False]
 [ True False  True ...  True False  True]
 [ True False  True ...  True  True False]
 ...
 [ True False  True ... False  True  True]
 [ True False False ... False  True False]
 [False  True  True ...  True False  True]], shape=(1000, 1000), dtype=bool)
tf.Tensor(
[[False  True  True ... False  True False]
 [False  True False ... False  True False]
 [False  True  True ...  True False  True]
 ...
 [ True False False ...  True False  True]
 [False False False ... False False  True]
 [ True False  True ...  True False  True]], shape=(1000, 1000), dtype=bool)
tf.Tensor(
[[False  True False ... False False False]
 [False False False ... False False False]
 [False False  True ...  True False False]
 ...
 [ True False False ... False False  True]
 [False False False ... False False False]
 [False False  True ...  True False  True]], shape=(1000, 1000), dtype=bool)
tf.Tensor(249983, shape=(), dtype=int32)


249983

In [12]:
import torch
print(torch.cuda.is_available())

# 2つのランダムなbool型行列を生成
matrix1 = torch.randint(0, 2, (1000, 1000), dtype=torch.bool)
matrix2 = torch.randint(0, 2, (1000, 1000), dtype=torch.bool)
print(matrix1)
print(matrix2)

matrix1 = matrix1.to('cuda')
matrix2 = matrix2.to('cuda')
print(matrix1)
print(matrix2)

# 論理積を計算
result = matrix1 & matrix2

# 結果を表示
print(result)

# Trueの要素の数を数える
true_count = result.sum().item()

# 結果を表示
print(true_count)

True
tensor([[False, False,  True,  ..., False, False,  True],
        [False, False, False,  ..., False, False,  True],
        [False,  True,  True,  ..., False, False, False],
        ...,
        [False, False, False,  ..., False,  True,  True],
        [ True,  True,  True,  ..., False,  True, False],
        [ True,  True, False,  ...,  True,  True, False]])
tensor([[False, False, False,  ..., False,  True,  True],
        [ True, False,  True,  ..., False,  True, False],
        [ True,  True,  True,  ..., False, False, False],
        ...,
        [False, False, False,  ..., False,  True, False],
        [ True, False,  True,  ..., False,  True, False],
        [False,  True, False,  ..., False, False, False]])
tensor([[False, False,  True,  ..., False, False,  True],
        [False, False, False,  ..., False, False,  True],
        [False,  True,  True,  ..., False, False, False],
        ...,
        [False, False, False,  ..., False,  True,  True],
        [ True,  True,  Tr

In [20]:
import torch

print(torch.cuda.is_available())

import time
# timeit: テンソルを二乗し、計算にかかった時間を表示する。
def timeit(x):
    t0 = time.time()
    x = torch.mm(x, x)
    dt = time.time() - t0
    #print(dt)
    return dt

# gpu
# 1000×1000のランダムな行列を二乗する。
x = torch.rand(1000,1000).to('cuda')
print(f'gpu 1000x1000 => {timeit(x)}')
# 10000×10000のランダムな行列を二乗する。
x = torch.rand(10000,10000).to('cuda')
print(f'gpu 10000x10000 => {timeit(x)}')

# cpu
# 1000×1000のランダムな行列を二乗する。
x = torch.rand(1000,1000)
print(f'cpu 1000x1000 => {timeit(x)}')
# 10000×10000のランダムな行列を二乗する。
x = torch.rand(10000,10000)
print(f'cpu 10000x10000 => {timeit(x)}')


True
gpu 1000x1000 => 0.00020456314086914062
gpu 10000x10000 => 0.0002148151397705078
cpu 1000x1000 => 0.14715957641601562
cpu 10000x10000 => 31.2896146774292


In [24]:
import torch
import time

# 行列のサイズ
size = 10000

# CPU上での計算
start_time_cpu = time.time()
matrix_cpu = torch.randn(size, size)
#matrix_cpu = torch.rand(size, size)
#result_cpu = matrix_cpu ** 2
result_cpu = torch.mm(matrix_cpu, matrix_cpu)
cpu_duration = time.time() - start_time_cpu

# GPU上での計算（CUDAが利用可能な場合）
if torch.cuda.is_available():
    start_time_gpu = time.time()
    matrix_gpu = torch.randn(size, size, device='cuda')
    #matrix_gpu = torch.rand(size, size, device='cuda')
    #result_gpu = matrix_gpu ** 2
    result_gpu = torch.mm(matrix_gpu, matrix_gpu)
    gpu_duration = time.time() - start_time_gpu
else:
    gpu_duration = None

print(f"CPU Duration: {cpu_duration} seconds")
if gpu_duration is not None:
    print(f"GPU Duration: {gpu_duration} seconds")
else:
    print("CUDA is not available.")

CPU Duration: 32.15000939369202 seconds
GPU Duration: 0.0003829002380371094 seconds
